package com.bonc.GESysServer.mybitis.model;

public class AreaInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_info.area_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private String areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_info.area_name
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_info.parent_area_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private String parentAreaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_info.area_level
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private Integer areaLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_info.area_order
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private Integer areaOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_info.status
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_info.area_id
     *
     * @return the value of area_info.area_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_info.area_id
     *
     * @param areaId the value for area_info.area_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_info.area_name
     *
     * @return the value of area_info.area_name
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_info.area_name
     *
     * @param areaName the value for area_info.area_name
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_info.parent_area_id
     *
     * @return the value of area_info.parent_area_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public String getParentAreaId() {
        return parentAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_info.parent_area_id
     *
     * @param parentAreaId the value for area_info.parent_area_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setParentAreaId(String parentAreaId) {
        this.parentAreaId = parentAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_info.area_level
     *
     * @return the value of area_info.area_level
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public Integer getAreaLevel() {
        return areaLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_info.area_level
     *
     * @param areaLevel the value for area_info.area_level
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setAreaLevel(Integer areaLevel) {
        this.areaLevel = areaLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_info.area_order
     *
     * @return the value of area_info.area_order
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public Integer getAreaOrder() {
        return areaOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_info.area_order
     *
     * @param areaOrder the value for area_info.area_order
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setAreaOrder(Integer areaOrder) {
        this.areaOrder = areaOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_info.status
     *
     * @return the value of area_info.status
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_info.status
     *
     * @param status the value for area_info.status
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}