package com.bonc.GESysServer.mybitis.model;

public class GroupRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_role.id
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_role.role_id
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_role.id
     *
     * @return the value of group_role.id
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_role.id
     *
     * @param id the value for group_role.id
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_role.role_id
     *
     * @return the value of group_role.role_id
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_role.role_id
     *
     * @param roleId the value for group_role.role_id
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
}