package com.bonc.GESysServer.mybitis.model;

import java.sql.Timestamp;

public class MenuInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.menu_id
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.menu_name
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.menu_level
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    private Integer menuLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.menu_order
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    private Integer menuOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.menu_desc
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    private String menuDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.parent_menu_id
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    private String parentMenuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.status
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.create_time
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    private Timestamp createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.menu_id
     *
     * @return the value of menu_info.menu_id
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.menu_id
     *
     * @param menuId the value for menu_info.menu_id
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.menu_name
     *
     * @return the value of menu_info.menu_name
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.menu_name
     *
     * @param menuName the value for menu_info.menu_name
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.menu_level
     *
     * @return the value of menu_info.menu_level
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public Integer getMenuLevel() {
        return menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.menu_level
     *
     * @param menuLevel the value for menu_info.menu_level
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public void setMenuLevel(Integer menuLevel) {
        this.menuLevel = menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.menu_order
     *
     * @return the value of menu_info.menu_order
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public Integer getMenuOrder() {
        return menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.menu_order
     *
     * @param menuOrder the value for menu_info.menu_order
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public void setMenuOrder(Integer menuOrder) {
        this.menuOrder = menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.menu_desc
     *
     * @return the value of menu_info.menu_desc
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public String getMenuDesc() {
        return menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.menu_desc
     *
     * @param menuDesc the value for menu_info.menu_desc
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public void setMenuDesc(String menuDesc) {
        this.menuDesc = menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.parent_menu_id
     *
     * @return the value of menu_info.parent_menu_id
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public String getParentMenuId() {
        return parentMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.parent_menu_id
     *
     * @param parentMenuId the value for menu_info.parent_menu_id
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public void setParentMenuId(String parentMenuId) {
        this.parentMenuId = parentMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.status
     *
     * @return the value of menu_info.status
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.status
     *
     * @param status the value for menu_info.status
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.create_time
     *
     * @return the value of menu_info.create_time
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.create_time
     *
     * @param createTime the value for menu_info.create_time
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }
}