package com.bonc.GESysServer.mybitis.model;

import java.sql.Timestamp;

public class SysLoginLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.flow_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private Integer flowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.manager_account
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private String managerAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.manager_name
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private String managerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.login_msg
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private String loginMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.login_ip
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private String loginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.operate_time
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private Timestamp operateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.flow_id
     *
     * @return the value of sys_login_log.flow_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public Integer getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.flow_id
     *
     * @param flowId the value for sys_login_log.flow_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setFlowId(Integer flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.manager_account
     *
     * @return the value of sys_login_log.manager_account
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public String getManagerAccount() {
        return managerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.manager_account
     *
     * @param managerAccount the value for sys_login_log.manager_account
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setManagerAccount(String managerAccount) {
        this.managerAccount = managerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.manager_name
     *
     * @return the value of sys_login_log.manager_name
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.manager_name
     *
     * @param managerName the value for sys_login_log.manager_name
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.login_msg
     *
     * @return the value of sys_login_log.login_msg
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public String getLoginMsg() {
        return loginMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.login_msg
     *
     * @param loginMsg the value for sys_login_log.login_msg
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setLoginMsg(String loginMsg) {
        this.loginMsg = loginMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.login_ip
     *
     * @return the value of sys_login_log.login_ip
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.login_ip
     *
     * @param loginIp the value for sys_login_log.login_ip
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.operate_time
     *
     * @return the value of sys_login_log.operate_time
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public Timestamp getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.operate_time
     *
     * @param operateTime the value for sys_login_log.operate_time
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setOperateTime(Timestamp operateTime) {
        this.operateTime = operateTime;
    }
}