package com.bonc.GESysServer.mybitis.model;

import java.sql.Timestamp;

public class SysMangerInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manger_info.manager_account
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private String managerAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manger_info.manager_name
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private String managerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manger_info.manager_pwd
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private String managerPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manger_info.manager_mobile
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private String managerMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manger_info.manager_email
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private String managerEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manger_info.create_time
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manger_info.status
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manger_info.last_login_time
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private Timestamp last_login_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manger_info.manager_account
     *
     * @return the value of sys_manger_info.manager_account
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public String getManagerAccount() {
        return managerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manger_info.manager_account
     *
     * @param managerAccount the value for sys_manger_info.manager_account
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setManagerAccount(String managerAccount) {
        this.managerAccount = managerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manger_info.manager_name
     *
     * @return the value of sys_manger_info.manager_name
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manger_info.manager_name
     *
     * @param managerName the value for sys_manger_info.manager_name
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manger_info.manager_pwd
     *
     * @return the value of sys_manger_info.manager_pwd
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public String getManagerPwd() {
        return managerPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manger_info.manager_pwd
     *
     * @param managerPwd the value for sys_manger_info.manager_pwd
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setManagerPwd(String managerPwd) {
        this.managerPwd = managerPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manger_info.manager_mobile
     *
     * @return the value of sys_manger_info.manager_mobile
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public String getManagerMobile() {
        return managerMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manger_info.manager_mobile
     *
     * @param managerMobile the value for sys_manger_info.manager_mobile
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setManagerMobile(String managerMobile) {
        this.managerMobile = managerMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manger_info.manager_email
     *
     * @return the value of sys_manger_info.manager_email
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public String getManagerEmail() {
        return managerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manger_info.manager_email
     *
     * @param managerEmail the value for sys_manger_info.manager_email
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setManagerEmail(String managerEmail) {
        this.managerEmail = managerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manger_info.create_time
     *
     * @return the value of sys_manger_info.create_time
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manger_info.create_time
     *
     * @param createTime the value for sys_manger_info.create_time
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manger_info.status
     *
     * @return the value of sys_manger_info.status
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manger_info.status
     *
     * @param status the value for sys_manger_info.status
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manger_info.last_login_time
     *
     * @return the value of sys_manger_info.last_login_time
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public Timestamp getLast_login_time() {
        return last_login_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manger_info.last_login_time
     *
     * @param last_login_time the value for sys_manger_info.last_login_time
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setLast_login_time(Timestamp last_login_time) {
        this.last_login_time = last_login_time;
    }
}