package com.bonc.GESysServer.mybitis.model;

import java.sql.Timestamp;

public class SysMenuInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_info.menu_id
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_info.menu_name
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_info.menu_path
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private String menuPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_info.parent_menu_id
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private String parentMenuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_info.create_user_id
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_info.status
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_info.creat_time
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private Timestamp creatTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_info.menu_id
     *
     * @return the value of sys_menu_info.menu_id
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_info.menu_id
     *
     * @param menuId the value for sys_menu_info.menu_id
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_info.menu_name
     *
     * @return the value of sys_menu_info.menu_name
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_info.menu_name
     *
     * @param menuName the value for sys_menu_info.menu_name
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_info.menu_path
     *
     * @return the value of sys_menu_info.menu_path
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public String getMenuPath() {
        return menuPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_info.menu_path
     *
     * @param menuPath the value for sys_menu_info.menu_path
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setMenuPath(String menuPath) {
        this.menuPath = menuPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_info.parent_menu_id
     *
     * @return the value of sys_menu_info.parent_menu_id
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public String getParentMenuId() {
        return parentMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_info.parent_menu_id
     *
     * @param parentMenuId the value for sys_menu_info.parent_menu_id
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setParentMenuId(String parentMenuId) {
        this.parentMenuId = parentMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_info.create_user_id
     *
     * @return the value of sys_menu_info.create_user_id
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_info.create_user_id
     *
     * @param createUserId the value for sys_menu_info.create_user_id
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_info.status
     *
     * @return the value of sys_menu_info.status
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_info.status
     *
     * @param status the value for sys_menu_info.status
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_info.creat_time
     *
     * @return the value of sys_menu_info.creat_time
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public Timestamp getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_info.creat_time
     *
     * @param creatTime the value for sys_menu_info.creat_time
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setCreatTime(Timestamp creatTime) {
        this.creatTime = creatTime;
    }
}