package com.bonc.GESysServer.mybitis.model;

public class SysManagerRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_role.manager_account
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    private String managerAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_manager_role.role_id
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_role.manager_account
     *
     * @return the value of sys_manager_role.manager_account
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public String getManagerAccount() {
        return managerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_role.manager_account
     *
     * @param managerAccount the value for sys_manager_role.manager_account
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public void setManagerAccount(String managerAccount) {
        this.managerAccount = managerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_manager_role.role_id
     *
     * @return the value of sys_manager_role.role_id
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_manager_role.role_id
     *
     * @param roleId the value for sys_manager_role.role_id
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
}