package com.bonc.GESysServer.mybitis.model;

import java.util.Date;

public class SysMenuRole extends SysMenuRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_role.create_time
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_role.auth_operate
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    private String authOperate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_role.create_time
     *
     * @return the value of sys_menu_role.create_time
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_role.create_time
     *
     * @param createTime the value for sys_menu_role.create_time
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_role.auth_operate
     *
     * @return the value of sys_menu_role.auth_operate
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public String getAuthOperate() {
        return authOperate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_role.auth_operate
     *
     * @param authOperate the value for sys_menu_role.auth_operate
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public void setAuthOperate(String authOperate) {
        this.authOperate = authOperate;
    }
}