package com.bonc.GESysServer.mybitis.model;

import java.util.Date;

public class SysMenuRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_role.flow_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private Integer flowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_role.role_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_role.menu_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_role.create_time
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu_role.auth_operate
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private String authOperate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_role.flow_id
     *
     * @return the value of sys_menu_role.flow_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public Integer getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_role.flow_id
     *
     * @param flowId the value for sys_menu_role.flow_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setFlowId(Integer flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_role.role_id
     *
     * @return the value of sys_menu_role.role_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_role.role_id
     *
     * @param roleId the value for sys_menu_role.role_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_role.menu_id
     *
     * @return the value of sys_menu_role.menu_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_role.menu_id
     *
     * @param menuId the value for sys_menu_role.menu_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_role.create_time
     *
     * @return the value of sys_menu_role.create_time
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_role.create_time
     *
     * @param createTime the value for sys_menu_role.create_time
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu_role.auth_operate
     *
     * @return the value of sys_menu_role.auth_operate
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public String getAuthOperate() {
        return authOperate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu_role.auth_operate
     *
     * @param authOperate the value for sys_menu_role.auth_operate
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setAuthOperate(String authOperate) {
        this.authOperate = authOperate;
    }
}