package com.bonc.GESysServer.mybitis.model;

import java.sql.Timestamp;

public class SysOperateLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operate_log.flow_id
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    private Integer flowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operate_log.manager_id
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    private String managerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operate_log.manager_name
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    private String managerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operate_log.operate_name
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    private String operateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operate_log.operate_time
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    private Timestamp operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_operate_log.operate_msg
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    private String operateMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operate_log.flow_id
     *
     * @return the value of sys_operate_log.flow_id
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public Integer getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operate_log.flow_id
     *
     * @param flowId the value for sys_operate_log.flow_id
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public void setFlowId(Integer flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operate_log.manager_id
     *
     * @return the value of sys_operate_log.manager_id
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operate_log.manager_id
     *
     * @param managerId the value for sys_operate_log.manager_id
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operate_log.manager_name
     *
     * @return the value of sys_operate_log.manager_name
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operate_log.manager_name
     *
     * @param managerName the value for sys_operate_log.manager_name
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operate_log.operate_name
     *
     * @return the value of sys_operate_log.operate_name
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public String getOperateName() {
        return operateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operate_log.operate_name
     *
     * @param operateName the value for sys_operate_log.operate_name
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public void setOperateName(String operateName) {
        this.operateName = operateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operate_log.operate_time
     *
     * @return the value of sys_operate_log.operate_time
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public Timestamp getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operate_log.operate_time
     *
     * @param operateTime the value for sys_operate_log.operate_time
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public void setOperateTime(Timestamp operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_operate_log.operate_msg
     *
     * @return the value of sys_operate_log.operate_msg
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public String getOperateMsg() {
        return operateMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_operate_log.operate_msg
     *
     * @param operateMsg the value for sys_operate_log.operate_msg
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    public void setOperateMsg(String operateMsg) {
        this.operateMsg = operateMsg;
    }
}