package com.bonc.GESysServer.mybitis.model;

public class UserGroupMemberKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group_member.group_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group_member.user_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group_member.group_id
     *
     * @return the value of user_group_member.group_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group_member.group_id
     *
     * @param groupId the value for user_group_member.group_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group_member.user_id
     *
     * @return the value of user_group_member.user_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group_member.user_id
     *
     * @param userId the value for user_group_member.user_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}