package com.bonc.GESysServer.mybitis.model;

import java.sql.Timestamp;

public class UserResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_resource.resource_id
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private String resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_resource.resource_name
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_resource.resource_value
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private String resourceValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_resource.resource_type
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private String resourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_resource.status
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_resource.create_time
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_resource.update_time
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private Timestamp updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_resource.operator
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    private String operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_resource.resource_id
     *
     * @return the value of user_resource.resource_id
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_resource.resource_id
     *
     * @param resourceId the value for user_resource.resource_id
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_resource.resource_name
     *
     * @return the value of user_resource.resource_name
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_resource.resource_name
     *
     * @param resourceName the value for user_resource.resource_name
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_resource.resource_value
     *
     * @return the value of user_resource.resource_value
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public String getResourceValue() {
        return resourceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_resource.resource_value
     *
     * @param resourceValue the value for user_resource.resource_value
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setResourceValue(String resourceValue) {
        this.resourceValue = resourceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_resource.resource_type
     *
     * @return the value of user_resource.resource_type
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_resource.resource_type
     *
     * @param resourceType the value for user_resource.resource_type
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_resource.status
     *
     * @return the value of user_resource.status
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_resource.status
     *
     * @param status the value for user_resource.status
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_resource.create_time
     *
     * @return the value of user_resource.create_time
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_resource.create_time
     *
     * @param createTime the value for user_resource.create_time
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_resource.update_time
     *
     * @return the value of user_resource.update_time
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_resource.update_time
     *
     * @param updateTime the value for user_resource.update_time
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_resource.operator
     *
     * @return the value of user_resource.operator
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_resource.operator
     *
     * @param operator the value for user_resource.operator
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }
}