package com.bonc.GESysServer.mybitis.model;

import java.sql.Timestamp;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_area_code
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private String userAreaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_mobile
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private String userMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.login_pwd
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private String loginPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.status
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.authority_time
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private Timestamp authorityTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_time
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private Timestamp updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.operator
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_time
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.last_login_time
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    private Timestamp lastLoginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_area_code
     *
     * @return the value of user_info.user_area_code
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public String getUserAreaCode() {
        return userAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_area_code
     *
     * @param userAreaCode the value for user_info.user_area_code
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setUserAreaCode(String userAreaCode) {
        this.userAreaCode = userAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_mobile
     *
     * @return the value of user_info.user_mobile
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_mobile
     *
     * @param userMobile the value for user_info.user_mobile
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.login_pwd
     *
     * @return the value of user_info.login_pwd
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.login_pwd
     *
     * @param loginPwd the value for user_info.login_pwd
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.status
     *
     * @return the value of user_info.status
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.status
     *
     * @param status the value for user_info.status
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.authority_time
     *
     * @return the value of user_info.authority_time
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public Timestamp getAuthorityTime() {
        return authorityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.authority_time
     *
     * @param authorityTime the value for user_info.authority_time
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setAuthorityTime(Timestamp authorityTime) {
        this.authorityTime = authorityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.update_time
     *
     * @return the value of user_info.update_time
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.update_time
     *
     * @param updateTime the value for user_info.update_time
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.operator
     *
     * @return the value of user_info.operator
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.operator
     *
     * @param operator the value for user_info.operator
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_time
     *
     * @return the value of user_info.create_time
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_time
     *
     * @param createTime the value for user_info.create_time
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.last_login_time
     *
     * @return the value of user_info.last_login_time
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public Timestamp getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.last_login_time
     *
     * @param lastLoginTime the value for user_info.last_login_time
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    public void setLastLoginTime(Timestamp lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }
}