package com.bonc.GESysServer.mybitis.mapper;

import com.bonc.GESysServer.mybitis.model.SysManagerInfo;
import com.bonc.GESysServer.mybitis.model.SysManagerInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysManagerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_info
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    int countByExample(SysManagerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_info
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    int deleteByExample(SysManagerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_info
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    int deleteByPrimaryKey(String managerAccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_info
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    int insert(SysManagerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_info
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    int insertSelective(SysManagerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_info
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    List<SysManagerInfo> selectByExample(SysManagerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_info
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    SysManagerInfo selectByPrimaryKey(String managerAccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_info
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    int updateByExampleSelective(@Param("record") SysManagerInfo record, @Param("example") SysManagerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_info
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    int updateByExample(@Param("record") SysManagerInfo record, @Param("example") SysManagerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_info
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    int updateByPrimaryKeySelective(SysManagerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manager_info
     *
     * @mbggenerated Fri Mar 14 00:08:14 CST 2014
     */
    int updateByPrimaryKey(SysManagerInfo record);
    
    /**
     * 根据用户信息查询对应的用户集合 
     * 
     * */
    List<SysManagerInfo> selectByParam(SysManagerInfo param);
}