package com.bonc.GESysServer.mybitis.mapper;

import com.bonc.GESysServer.mybitis.model.SysMenuInfo;
import com.bonc.GESysServer.mybitis.model.SysMenuInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysMenuInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_info
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int countByExample(SysMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_info
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int deleteByExample(SysMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_info
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int deleteByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_info
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int insert(SysMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_info
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int insertSelective(SysMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_info
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    List<SysMenuInfo> selectByExample(SysMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_info
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    SysMenuInfo selectByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_info
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int updateByExampleSelective(@Param("record") SysMenuInfo record, @Param("example") SysMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_info
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int updateByExample(@Param("record") SysMenuInfo record, @Param("example") SysMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_info
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int updateByPrimaryKeySelective(SysMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_info
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int updateByPrimaryKey(SysMenuInfo record);
}