package com.bonc.GESysServer.mybitis.mapper;

import com.bonc.GESysServer.mybitis.model.SysMangerInfo;
import com.bonc.GESysServer.mybitis.model.SysMangerInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysMangerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manger_info
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    int countByExample(SysMangerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manger_info
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    int deleteByExample(SysMangerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manger_info
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    int deleteByPrimaryKey(String managerAccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manger_info
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    int insert(SysMangerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manger_info
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    int insertSelective(SysMangerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manger_info
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    List<SysMangerInfo> selectByExample(SysMangerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manger_info
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    SysMangerInfo selectByPrimaryKey(String managerAccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manger_info
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    int updateByExampleSelective(@Param("record") SysMangerInfo record, @Param("example") SysMangerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manger_info
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    int updateByExample(@Param("record") SysMangerInfo record, @Param("example") SysMangerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manger_info
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    int updateByPrimaryKeySelective(SysMangerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_manger_info
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    int updateByPrimaryKey(SysMangerInfo record);
}