package com.bonc.GESysServer.mybitis.mapper;

import com.bonc.GESysServer.mybitis.model.SysOperateLog;
import com.bonc.GESysServer.mybitis.model.SysOperateLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysOperateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate_log
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int countByExample(SysOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate_log
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int deleteByExample(SysOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate_log
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int deleteByPrimaryKey(Integer flowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate_log
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int insert(SysOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate_log
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int insertSelective(SysOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate_log
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    List<SysOperateLog> selectByExample(SysOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate_log
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    SysOperateLog selectByPrimaryKey(Integer flowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate_log
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int updateByExampleSelective(@Param("record") SysOperateLog record, @Param("example") SysOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate_log
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int updateByExample(@Param("record") SysOperateLog record, @Param("example") SysOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate_log
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int updateByPrimaryKeySelective(SysOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_operate_log
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int updateByPrimaryKey(SysOperateLog record);
}