package com.bonc.GESysServer.mybitis.mapper;

import com.bonc.GESysServer.mybitis.model.UserOperateLog;
import com.bonc.GESysServer.mybitis.model.UserOperateLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserOperateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    int countByExample(UserOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    int deleteByExample(UserOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    int deleteByPrimaryKey(Integer flowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    int insert(UserOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    int insertSelective(UserOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    List<UserOperateLog> selectByExample(UserOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    UserOperateLog selectByPrimaryKey(Integer flowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    int updateByExampleSelective(@Param("record") UserOperateLog record, @Param("example") UserOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    int updateByExample(@Param("record") UserOperateLog record, @Param("example") UserOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    int updateByPrimaryKeySelective(UserOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbggenerated Wed Mar 12 23:43:34 CST 2014
     */
    int updateByPrimaryKey(UserOperateLog record);
}