package com.bonc.GESysServer.mybitis.mapper;

import com.bonc.GESysServer.mybitis.model.UserResource;
import com.bonc.GESysServer.mybitis.model.UserResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int countByExample(UserResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int deleteByExample(UserResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int deleteByPrimaryKey(String resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int insert(UserResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int insertSelective(UserResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    List<UserResource> selectByExample(UserResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    UserResource selectByPrimaryKey(String resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int updateByExampleSelective(@Param("record") UserResource record, @Param("example") UserResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int updateByExample(@Param("record") UserResource record, @Param("example") UserResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int updateByPrimaryKeySelective(UserResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int updateByPrimaryKey(UserResource record);
}