package com.bonc.GESysServer.mybitis.mapper;

import com.bonc.GESysServer.mybitis.model.UserGroupMemberExample;
import com.bonc.GESysServer.mybitis.model.UserGroupMemberKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserGroupMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group_member
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int countByExample(UserGroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group_member
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int deleteByExample(UserGroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group_member
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int deleteByPrimaryKey(UserGroupMemberKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group_member
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int insert(UserGroupMemberKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group_member
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int insertSelective(UserGroupMemberKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group_member
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    List<UserGroupMemberKey> selectByExample(UserGroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group_member
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int updateByExampleSelective(@Param("record") UserGroupMemberKey record, @Param("example") UserGroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group_member
     *
     * @mbggenerated Thu Mar 13 23:40:39 CST 2014
     */
    int updateByExample(@Param("record") UserGroupMemberKey record, @Param("example") UserGroupMemberExample example);
}